# Solution to the February 2026 Jane Street Puzzle

The puzzle features a large amount of expressions, each of which must be a positive integer in the set of 1 to 13

My approach is to first solve for the clues, i.e. the numbers. 

In [1]:
import numpy as np
import sympy as sp
import math
np.set_printoptions(linewidth = 200)

In [2]:
arr = np.array([[0 for _ in range(13)] for _ in range(13)], dtype = object)
print(arr)

[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [3]:
a, b, c = sp.symbols('a b c')

In [4]:
arr[0, 4] = 6*c - 4*b

arr[1, 7] = 8 - b

arr[2, 1] = (sp.Pow(a, b) - 4)/(6*c + 1)
arr[2, 3] = (b+c)/(c-1)
arr[2, 6] = sp.Pow(b, 2) - (b/c)
arr[2, 8] = sp.sqrt(30+a)/c
arr[2, 10] = (a+b)/(c-3*a)

arr[3, 4] = (b-3*a)/(a-c)
arr[3, 7] = 8*a - 2*b
arr[3, 9] = b / (a-c)
arr[3, 11] = (b+9)/(sp.sqrt(c-a))

arr[4, 1] = 18/(a*c + 1)
arr[4, 5] = sp.Pow(c, b)
arr[4, 10] = (3 + sp.Pow(b, 2))/(sp.sqrt(3 + 2*c))

arr[5, 3] = b/(sp.Pow(a, 2) - sp.Pow(c, 2))
arr[5, 12] = sp.sqrt(a + 2)/a

arr[6, 2] = sp.Pow(a, b) - (12/a)
arr[6, 4] = 2*c + c/a
arr[6, 6] = 4*a-5*b
arr[6, 8] = c + 2*a
arr[6, 10] = b / (9*a - 5*c)

arr[7, 0] = (sp.Pow(b, 3) + 2*c)/(b + 2*c)
arr[7, 9] = b / (a-1)

arr[8, 2] = (c-b)/(2*a)
arr[8, 7] = b / (a-c)
arr[8, 11] = (b+c)/(a-c)

arr[9, 1] = sp.log(a, c)
arr[9, 3] = (sp.Pow(c, 2) - b)/a
arr[9, 5] = sp.Pow(b-1, 2)
arr[9, 8] = sp.cbrt(43 - a*c)/a

arr[10, 2] = (b-a)/(a-c)
arr[10, 4] = 11-b
arr[10, 6] = (b-2*a)/(a-c)
arr[10, 9] = (c+3)/a
arr[10, 11] = 8*c - b/c

arr[11, 5] = sp.Pow(b, 2)

arr[12, 8] = (sp.Pow(2, b) + 1)/(a*c)

In [5]:
sp.init_printing()
arr

array([[0, 0, 0, 0, -4*b + 6*c, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 8 - b, 0, 0, 0, 0, 0],
       [0, (a**b - 4)/(6*c + 1), 0, (b + c)/(c - 1), 0, 0, b**2 - b/c, 0, sqrt(a + 30)/c, 0, (a + b)/(-3*a + c), 0, 0],
       [0, 0, 0, 0, (-3*a + b)/(a - c), 0, 0, 8*a - 2*b, 0, b/(a - c), 0, (b + 9)/sqrt(-a + c), 0],
       [0, 18/(a*c + 1), 0, 0, 0, c**b, 0, 0, 0, 0, (b**2 + 3)/sqrt(2*c + 3), 0, 0],
       [0, 0, 0, b/(a**2 - c**2), 0, 0, 0, 0, 0, 0, 0, 0, sqrt(a + 2)/a],
       [0, 0, a**b - 12/a, 0, 2*c + c/a, 0, 4*a - 5*b, 0, 2*a + c, 0, b/(9*a - 5*c), 0, 0],
       [(b**3 + 2*c)/(b + 2*c), 0, 0, 0, 0, 0, 0, 0, 0, b/(a - 1), 0, 0, 0],
       [0, 0, (-b + c)/(2*a), 0, 0, 0, 0, b/(a - c), 0, 0, 0, (b + c)/(a - c), 0],
       [0, log(a)/log(c), 0, (-b + c**2)/a, 0, (b - 1)**2, 0, 0, (-a*c + 43)**(1/3)/a, 0, 0, 0, 0],
       [0, 0, (-a + b)/(a - c), 0, 11 - b, 0, (-2*a + b)/(a - c), 0, 0, (c + 3)/a, 0, -b/c + 8*c, 0],
       [0, 0, 0, 0, 0, b**2, 0, 0, 0, 0, 0, 0, 0],
       

In [6]:
# parameters
vals = {a: 0, b: 0, c: 0}

def substitute_cell(x, vals):
    if x is None:
        return None
    if isinstance(x, sp.Basic):
        y = x.subs(vals)
        try:
            return sp.N(y)     # numeric result
        except Exception:
            return y
    if callable(x):
        try:
            return x(vals.get(a), vals.get(b), vals.get(c))
        except Exception:
            return x
    return x

def to_real_if_possible(v, tol=1e-8):
    if v is None:
        return None
    # Python complex
    if isinstance(v, complex):
        return v.real if abs(v.imag) < tol else v
    # SymPy numeric or other numeric-like
    try:
        z = complex(v)           # works for SymPy complex/real and numpy scalars
        if abs(z.imag) < tol:
            return z.real
    except Exception:
        pass
    # fallback: return as-is
    return v

In [12]:
from itertools import product

# faster evaluation by compiling sympy expressions to numeric callables and skipping zeros

# prepare compiled entries for non-zero cells
_entries = []
for idx, x in np.ndenumerate(arr):
  if x == 0 or x is None:
    continue
  if isinstance(x, sp.Basic):
    try:
      f = sp.lambdify((a, b, c), x, modules="math")
      _entries.append((idx, "func", f))
    except Exception:
      _entries.append((idx, "expr", x))
  else:
    _entries.append((idx, "const", x))

def evaluate_triple_fast(aval, bval, cval, tol=1e-3):
  vals_local = {a: aval, b: bval, c: cval}
  num_arr = np.zeros(arr.shape, dtype=object)
  nonint_count = 0

  for idx, kind, payload in _entries:
    try:
      if kind == "func":
        raw = payload(aval, bval, cval)
      elif kind == "expr":
        raw = substitute_cell(payload, vals_local)
        raw = to_real_if_possible(raw, tol=tol)
      else:  # const
        raw = payload
    except Exception:
      nonint_count += 1
      num_arr[idx] = None
      continue

    if raw is None:
      num_arr[idx] = None
      continue

    # coerce numpy / sympy scalars to Python numbers where possible
    try:
      z = complex(raw)
    except Exception:
      nonint_count += 1
      num_arr[idx] = raw
      continue

    if not (math.isfinite(z.real) and math.isfinite(z.imag)) or abs(z.imag) > tol:
      nonint_count += 1
      num_arr[idx] = raw
      continue

    val_real = z.real
    if math.isclose(val_real, round(val_real), abs_tol=tol):
      val = int(round(val_real))
    else:
      nonint_count += 1
      val = val_real

    num_arr[idx] = val

  return num_arr, nonint_count

def search(a_vals, b_vals, c_vals, tol=1e-3, report_limit=50):
  matches = []
  printed = 0
  for aval, bval, cval in product(a_vals, b_vals, c_vals):
    num_arr, nonint_count = evaluate_triple_fast(aval, bval, cval, tol=tol)
    if nonint_count == 0:
      matches.append((aval, bval, cval, num_arr))
      if printed < report_limit:
        print("match:", (aval, bval, cval))
        printed += 1
  return matches

# run search over the existing ranges
results = search(a_vals = range(-100, 101), b_vals = range(-10, 11), c_vals = range(-100, 101))
len(results)
